# .github/workflows/build-macos-app.yml

name: Build SELFIX macOS .app

on:
  push:
    branches: [main]

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Build Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app
          pip install -r requirements.txt

      - name: 🛠️ Build .app with py2app
        run: |
          python3 setup.py py2app

      - name: 📤 Upload macOS .app Artifact
        uses: actions/upload-artifact@v4  # ✅ updated from @v3 to @v4
        with:
          name: selfix-macos-app
          path: dist/*.app
