name: Build SELFIX macOS App

on:
  push:
    branches: [main]

jobs:
  build-mac-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install py2app macholib

      - name: Build macOS app with py2app
        run: |
          python3 setup.py py2app

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Create DMG installer
        run: |
          create-dmg \
            --volname "SELFIX Installer" \
            --window-pos 200 120 \
            --window-size 500 300 \
            --icon-size 100 \
            --icon "selfix_gui.app" 125 150 \
            --app-drop-link 375 150 \
            "dist/SELFIX.dmg" \
            "dist/"

      - name: Upload .app and .dmg as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SELFIX-mac-build
          path: |
            dist/selfix_gui.app
            dist/SELFIX.dmg
