name: Release SELFIX App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.1.0

jobs:
  build-windows:
    name: 🪟 Build Windows EXE + ZIP
    runs-on: windows-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller
          pip install -r requirements.txt

      - name: 🏗️ Build EXE with PyInstaller
        run: |
          pyinstaller --onefile selfix_gui.py

      - name: 📦 Package ZIP
        run: |
          echo "SELFIX v${{ github.ref_name }}" > README.txt
          powershell -Command "Compress-Archive -Path dist/selfix_gui.exe, README.txt -DestinationPath dist/SELFIX-${{ github.ref_name }}.zip"

      - name: ☁️ Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selfix-windows
          path: |
            dist/selfix_gui.exe
            dist/SELFIX-${{ github.ref_name }}.zip

  build-macos:
    name: 🍎 Build macOS .app + .dmg
    runs-on: macos-latest
    needs: build-windows

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          brew install create-dmg || true
          npm install -g create-dmg || true
          python3 -m pip install --upgrade pip setuptools wheel
          pip install py2app
          pip install -r requirements.txt

      - name: 🛠️ Build macOS .app
        run: |
          python3 setup.py py2app

      - name: 📦 Build .dmg Installer
        run: |
          create-dmg \
            "dist/SELFIX.app" \
            --overwrite \
            --volname "SELFIX" \
            --dmg-title "SELFIX Installer" \
            --app-drop-link 200 200 \
            --icon "SELFIX.app" 100 100 \
            --window-size 500 300 \
            --quit-after-done \
            dist/

      - name: ☁️ Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selfix-macos
          path: |
            dist/*.app
            dist/*.dmg

  release:
    name: 🚀 Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ⬇️ Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: selfix-windows
          path: ./release-assets

      - name: ⬇️ Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: selfix-macos
          path: ./release-assets

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "SELFIX ${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
          token: ${{ secrets.GH_PAT }}
          draft: false
          prerelease: false
          files: |
            release-assets/selfix_gui.exe
            release-assets/SELFIX-${{ github.ref_name }}.zip
            release-assets/*.app
            release-assets/*.dmg
