name: Release SELFIX App

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

jobs:
  build-windows:
    name: Build Windows EXE + ZIP
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile selfix_gui.py

      - name: Package EXE into ZIP
        run: |
          Compress-Archive -Path dist/selfix_gui.exe -DestinationPath dist/selfix_gui.zip

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4  # 游대 FIXED
        with:
          name: selfix-windows-artifacts
          path: |
            dist/selfix_gui.exe
            dist/selfix_gui.zip

  build-macos:
    name: Build macOS .app + .dmg
    runs-on: macos-latest
    needs: build-windows

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install py2app
          pip install -r requirements.txt
          brew install create-dmg || true
          npm install -g create-dmg

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Build .dmg Installer
        run: |
          create-dmg dist/SELFIX.app \
            --overwrite \
            --dmg-title="SELFIX Installer" \
            --volname="SELFIX" \
            --app-drop-link 200 200 \
            --window-size 500 300 \
            ./dist

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4  # 游대 FIXED
        with:
          name: selfix-macos-artifacts
          path: |
            dist/*.app
            dist/*.dmg

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]

    steps:
      - uses: actions/checkout@v3

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4  # 游대 FIXED
        with:
          name: selfix-windows-artifacts
          path: ./release-assets

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4  # 游대 FIXED
        with:
          name: selfix-macos-artifacts
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "SELFIX Release ${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
          token: ${{ secrets.GH_PAT }}
          draft: false
          prerelease: false
          files: |
            release-assets/selfix_gui.exe
            release-assets/selfix_gui.zip
            release-assets/*.app
            release-assets/*.dmg
