name: 🚀 Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout source code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install py2app

      - name: 🧹 Clean previous builds
        run: rm -rf build dist

      - name: ⚙️ Build macOS app with py2app
        run: python3 setup.py py2app

      - name: 🚀 Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: dist/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # ✅ Your PAT secret
